# Домашнее задание 3 "Продвинутая линейная алгебра".

Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [1]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

In [22]:
# a) Диагональная, ортогональная, но не единичная(!)
A = np.diag([1,-1])
A
# AT = A.transpose()
# A.dot(AT)


array([[ 1,  0],
       [ 0, -1]])

In [47]:
# b) Верхнетреугольная, ортогональная
B = np.array([[1, 0],[0, -1]])
B
# BT = B.transpose()
# B.dot(BT)

array([[1, 0],
       [0, 1]])

In [49]:
#c) Нижнетреугольная, ортогональная
C = np.array([[1, 0],[0, -1]])
C
# CT = C.transpose()
# C.dot(CT)

array([[1, 0],
       [0, 1]])

In [13]:
CT = C.transpose()
C.dot(CT)

array([[1, 1],
       [1, 2]])

In [35]:
#d) Матрица, у которой определитель = 1, и все элементы не равны 0
m = np.array([[2, 1], [1, 1]])
det = np.linalg.det(m)
print(m)
print(det)

[[2 1]
 [1 1]]
1.0
